# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b64e4800e5ad762b5ccb222bcd665acffe63d3453aabea0a026e0dbb05f9314f45d47174f106aa0638085907bffaf1e1dae5e4c26eadac9155e95a741db2238

test:
  secret_key_base: f4531af83e4fc1218a4038d8129d44283398bf47da39abff3986591fadef98bc84bcdf177b691343dfd9b9eaf65df2a5e03b33725c54bdd75d9b265ba8940f77

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
